package se.vgregion.domain.logging;

public enum UserAction {
    SEARCH_PATIENT,
    ATTEST_RELATION,
    ATTEST_CONSENT,
    EMERGENCY_CONSENT,
    REVEAL_BLOCKED,
    PASS_BLOCKED,
    EMERGENCY_PASS_BLOCKED,
    REVEAL_OTHER_UNITS,
    REVEAL_OTHER_PROVIDER,
    SUMMARY_CARE_SYSTEMS,
    ENTER_CARE_SYSTEM
}
