package se.vgregion.domain.logging;

public enum UserAction {
    SEARCH,
    RELATION,
    CONSENT,
    CONSENT_EMERGENCY,
    BLOCK,
    BLOCK_EMERGENCY,
    OTHER_CARE_UNITS,
    OTHER_CARE_PROVIDERS,
    INFORMATION_CHOICE,
    SHOW_BLOCKED_INFORMATION,
    SHOW_BLOCKED_INFORMATIONTYPE
}
